# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/martu/Facu/Taller I/Taller-Worms"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/martu/Facu/Taller I/Taller-Worms"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/martu/Facu/Taller I/Taller-Worms/CMakeFiles" "/home/martu/Facu/Taller I/Taller-Worms//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/martu/Facu/Taller I/Taller-Worms/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ui

# Build rule for target.
ui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ui
.PHONY : ui

# fast build rule for target.
ui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/build
.PHONY : ui/fast

#=============================================================================
# Target rules for targets named SharedGameLib

# Build rule for target.
SharedGameLib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SharedGameLib
.PHONY : SharedGameLib

# fast build rule for target.
SharedGameLib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedGameLib.dir/build.make CMakeFiles/SharedGameLib.dir/build
.PHONY : SharedGameLib/fast

#=============================================================================
# Target rules for targets named SharedLib

# Build rule for target.
SharedLib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SharedLib
.PHONY : SharedLib

# fast build rule for target.
SharedLib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedLib.dir/build.make CMakeFiles/SharedLib.dir/build
.PHONY : SharedLib/fast

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

#=============================================================================
# Target rules for targets named box2d

# Build rule for target.
box2d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 box2d
.PHONY : box2d

# fast build rule for target.
box2d/fast:
	$(MAKE) $(MAKESILENT) -f thirdParty/box2d/src/CMakeFiles/box2d.dir/build.make thirdParty/box2d/src/CMakeFiles/box2d.dir/build
.PHONY : box2d/fast

#=============================================================================
# Target rules for targets named unit_test

# Build rule for target.
unit_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit_test
.PHONY : unit_test

# fast build rule for target.
unit_test/fast:
	$(MAKE) $(MAKESILENT) -f thirdParty/box2d/unit-test/CMakeFiles/unit_test.dir/build.make thirdParty/box2d/unit-test/CMakeFiles/unit_test.dir/build
.PHONY : unit_test/fast

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) $(MAKESILENT) -f thirdParty/box2d/extern/glad/CMakeFiles/glad.dir/build.make thirdParty/box2d/extern/glad/CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f thirdParty/box2d/extern/glfw/CMakeFiles/glfw.dir/build.make thirdParty/box2d/extern/glfw/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) $(MAKESILENT) -f thirdParty/box2d/extern/imgui/CMakeFiles/imgui.dir/build.make thirdParty/box2d/extern/imgui/CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

#=============================================================================
# Target rules for targets named sajson

# Build rule for target.
sajson: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sajson
.PHONY : sajson

# fast build rule for target.
sajson/fast:
	$(MAKE) $(MAKESILENT) -f thirdParty/box2d/extern/sajson/CMakeFiles/sajson.dir/build.make thirdParty/box2d/extern/sajson/CMakeFiles/sajson.dir/build
.PHONY : sajson/fast

#=============================================================================
# Target rules for targets named testbed

# Build rule for target.
testbed: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testbed
.PHONY : testbed

# fast build rule for target.
testbed/fast:
	$(MAKE) $(MAKESILENT) -f thirdParty/box2d/testbed/CMakeFiles/testbed.dir/build.make thirdParty/box2d/testbed/CMakeFiles/testbed.dir/build
.PHONY : testbed/fast

#=============================================================================
# Target rules for targets named SDL2pp

# Build rule for target.
SDL2pp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2pp
.PHONY : SDL2pp

# fast build rule for target.
SDL2pp/fast:
	$(MAKE) $(MAKESILENT) -f thirdParty/SDL2pp/CMakeFiles/SDL2pp.dir/build.make thirdParty/SDL2pp/CMakeFiles/SDL2pp.dir/build
.PHONY : SDL2pp/fast

client_src/client.o: client_src/client.cpp.o
.PHONY : client_src/client.o

# target to build an object file
client_src/client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client_src/client.cpp.o
.PHONY : client_src/client.cpp.o

client_src/client.i: client_src/client.cpp.i
.PHONY : client_src/client.i

# target to preprocess a source file
client_src/client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client_src/client.cpp.i
.PHONY : client_src/client.cpp.i

client_src/client.s: client_src/client.cpp.s
.PHONY : client_src/client.s

# target to generate assembly for a file
client_src/client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client_src/client.cpp.s
.PHONY : client_src/client.cpp.s

client_src/client_main.o: client_src/client_main.cpp.o
.PHONY : client_src/client_main.o

# target to build an object file
client_src/client_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client_src/client_main.cpp.o
.PHONY : client_src/client_main.cpp.o

client_src/client_main.i: client_src/client_main.cpp.i
.PHONY : client_src/client_main.i

# target to preprocess a source file
client_src/client_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client_src/client_main.cpp.i
.PHONY : client_src/client_main.cpp.i

client_src/client_main.s: client_src/client_main.cpp.s
.PHONY : client_src/client_main.s

# target to generate assembly for a file
client_src/client_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client_src/client_main.cpp.s
.PHONY : client_src/client_main.cpp.s

client_src/receiver.o: client_src/receiver.cpp.o
.PHONY : client_src/receiver.o

# target to build an object file
client_src/receiver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client_src/receiver.cpp.o
.PHONY : client_src/receiver.cpp.o

client_src/receiver.i: client_src/receiver.cpp.i
.PHONY : client_src/receiver.i

# target to preprocess a source file
client_src/receiver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client_src/receiver.cpp.i
.PHONY : client_src/receiver.cpp.i

client_src/receiver.s: client_src/receiver.cpp.s
.PHONY : client_src/receiver.s

# target to generate assembly for a file
client_src/receiver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client_src/receiver.cpp.s
.PHONY : client_src/receiver.cpp.s

client_src/sender.o: client_src/sender.cpp.o
.PHONY : client_src/sender.o

# target to build an object file
client_src/sender.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client_src/sender.cpp.o
.PHONY : client_src/sender.cpp.o

client_src/sender.i: client_src/sender.cpp.i
.PHONY : client_src/sender.i

# target to preprocess a source file
client_src/sender.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client_src/sender.cpp.i
.PHONY : client_src/sender.cpp.i

client_src/sender.s: client_src/sender.cpp.s
.PHONY : client_src/sender.s

# target to generate assembly for a file
client_src/sender.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client_src/sender.cpp.s
.PHONY : client_src/sender.cpp.s

game_src/beam.o: game_src/beam.cpp.o
.PHONY : game_src/beam.o

# target to build an object file
game_src/beam.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedGameLib.dir/build.make CMakeFiles/SharedGameLib.dir/game_src/beam.cpp.o
.PHONY : game_src/beam.cpp.o

game_src/beam.i: game_src/beam.cpp.i
.PHONY : game_src/beam.i

# target to preprocess a source file
game_src/beam.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedGameLib.dir/build.make CMakeFiles/SharedGameLib.dir/game_src/beam.cpp.i
.PHONY : game_src/beam.cpp.i

game_src/beam.s: game_src/beam.cpp.s
.PHONY : game_src/beam.s

# target to generate assembly for a file
game_src/beam.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedGameLib.dir/build.make CMakeFiles/SharedGameLib.dir/game_src/beam.cpp.s
.PHONY : game_src/beam.cpp.s

game_src/game_dynamic.o: game_src/game_dynamic.cpp.o
.PHONY : game_src/game_dynamic.o

# target to build an object file
game_src/game_dynamic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedGameLib.dir/build.make CMakeFiles/SharedGameLib.dir/game_src/game_dynamic.cpp.o
.PHONY : game_src/game_dynamic.cpp.o

game_src/game_dynamic.i: game_src/game_dynamic.cpp.i
.PHONY : game_src/game_dynamic.i

# target to preprocess a source file
game_src/game_dynamic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedGameLib.dir/build.make CMakeFiles/SharedGameLib.dir/game_src/game_dynamic.cpp.i
.PHONY : game_src/game_dynamic.cpp.i

game_src/game_dynamic.s: game_src/game_dynamic.cpp.s
.PHONY : game_src/game_dynamic.s

# target to generate assembly for a file
game_src/game_dynamic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedGameLib.dir/build.make CMakeFiles/SharedGameLib.dir/game_src/game_dynamic.cpp.s
.PHONY : game_src/game_dynamic.cpp.s

game_src/game_lobby.o: game_src/game_lobby.cpp.o
.PHONY : game_src/game_lobby.o

# target to build an object file
game_src/game_lobby.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedGameLib.dir/build.make CMakeFiles/SharedGameLib.dir/game_src/game_lobby.cpp.o
.PHONY : game_src/game_lobby.cpp.o

game_src/game_lobby.i: game_src/game_lobby.cpp.i
.PHONY : game_src/game_lobby.i

# target to preprocess a source file
game_src/game_lobby.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedGameLib.dir/build.make CMakeFiles/SharedGameLib.dir/game_src/game_lobby.cpp.i
.PHONY : game_src/game_lobby.cpp.i

game_src/game_lobby.s: game_src/game_lobby.cpp.s
.PHONY : game_src/game_lobby.s

# target to generate assembly for a file
game_src/game_lobby.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedGameLib.dir/build.make CMakeFiles/SharedGameLib.dir/game_src/game_lobby.cpp.s
.PHONY : game_src/game_lobby.cpp.s

game_src/game_map.o: game_src/game_map.cpp.o
.PHONY : game_src/game_map.o

# target to build an object file
game_src/game_map.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedGameLib.dir/build.make CMakeFiles/SharedGameLib.dir/game_src/game_map.cpp.o
.PHONY : game_src/game_map.cpp.o

game_src/game_map.i: game_src/game_map.cpp.i
.PHONY : game_src/game_map.i

# target to preprocess a source file
game_src/game_map.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedGameLib.dir/build.make CMakeFiles/SharedGameLib.dir/game_src/game_map.cpp.i
.PHONY : game_src/game_map.cpp.i

game_src/game_map.s: game_src/game_map.cpp.s
.PHONY : game_src/game_map.s

# target to generate assembly for a file
game_src/game_map.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedGameLib.dir/build.make CMakeFiles/SharedGameLib.dir/game_src/game_map.cpp.s
.PHONY : game_src/game_map.cpp.s

game_src/move.o: game_src/move.cpp.o
.PHONY : game_src/move.o

# target to build an object file
game_src/move.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedGameLib.dir/build.make CMakeFiles/SharedGameLib.dir/game_src/move.cpp.o
.PHONY : game_src/move.cpp.o

game_src/move.i: game_src/move.cpp.i
.PHONY : game_src/move.i

# target to preprocess a source file
game_src/move.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedGameLib.dir/build.make CMakeFiles/SharedGameLib.dir/game_src/move.cpp.i
.PHONY : game_src/move.cpp.i

game_src/move.s: game_src/move.cpp.s
.PHONY : game_src/move.s

# target to generate assembly for a file
game_src/move.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedGameLib.dir/build.make CMakeFiles/SharedGameLib.dir/game_src/move.cpp.s
.PHONY : game_src/move.cpp.s

game_src/position.o: game_src/position.cpp.o
.PHONY : game_src/position.o

# target to build an object file
game_src/position.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedGameLib.dir/build.make CMakeFiles/SharedGameLib.dir/game_src/position.cpp.o
.PHONY : game_src/position.cpp.o

game_src/position.i: game_src/position.cpp.i
.PHONY : game_src/position.i

# target to preprocess a source file
game_src/position.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedGameLib.dir/build.make CMakeFiles/SharedGameLib.dir/game_src/position.cpp.i
.PHONY : game_src/position.cpp.i

game_src/position.s: game_src/position.cpp.s
.PHONY : game_src/position.s

# target to generate assembly for a file
game_src/position.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedGameLib.dir/build.make CMakeFiles/SharedGameLib.dir/game_src/position.cpp.s
.PHONY : game_src/position.cpp.s

game_src/select_map.o: game_src/select_map.cpp.o
.PHONY : game_src/select_map.o

# target to build an object file
game_src/select_map.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedGameLib.dir/build.make CMakeFiles/SharedGameLib.dir/game_src/select_map.cpp.o
.PHONY : game_src/select_map.cpp.o

game_src/select_map.i: game_src/select_map.cpp.i
.PHONY : game_src/select_map.i

# target to preprocess a source file
game_src/select_map.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedGameLib.dir/build.make CMakeFiles/SharedGameLib.dir/game_src/select_map.cpp.i
.PHONY : game_src/select_map.cpp.i

game_src/select_map.s: game_src/select_map.cpp.s
.PHONY : game_src/select_map.s

# target to generate assembly for a file
game_src/select_map.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedGameLib.dir/build.make CMakeFiles/SharedGameLib.dir/game_src/select_map.cpp.s
.PHONY : game_src/select_map.cpp.s

game_src/worm.o: game_src/worm.cpp.o
.PHONY : game_src/worm.o

# target to build an object file
game_src/worm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedGameLib.dir/build.make CMakeFiles/SharedGameLib.dir/game_src/worm.cpp.o
.PHONY : game_src/worm.cpp.o

game_src/worm.i: game_src/worm.cpp.i
.PHONY : game_src/worm.i

# target to preprocess a source file
game_src/worm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedGameLib.dir/build.make CMakeFiles/SharedGameLib.dir/game_src/worm.cpp.i
.PHONY : game_src/worm.cpp.i

game_src/worm.s: game_src/worm.cpp.s
.PHONY : game_src/worm.s

# target to generate assembly for a file
game_src/worm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedGameLib.dir/build.make CMakeFiles/SharedGameLib.dir/game_src/worm.cpp.s
.PHONY : game_src/worm.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/main.cpp.s
.PHONY : main.cpp.s

screen.o: screen.cpp.o
.PHONY : screen.o

# target to build an object file
screen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/screen.cpp.o
.PHONY : screen.cpp.o

screen.i: screen.cpp.i
.PHONY : screen.i

# target to preprocess a source file
screen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/screen.cpp.i
.PHONY : screen.cpp.i

screen.s: screen.cpp.s
.PHONY : screen.s

# target to generate assembly for a file
screen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/screen.cpp.s
.PHONY : screen.cpp.s

server_src/game_loop.o: server_src/game_loop.cpp.o
.PHONY : server_src/game_loop.o

# target to build an object file
server_src/game_loop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server_src/game_loop.cpp.o
.PHONY : server_src/game_loop.cpp.o

server_src/game_loop.i: server_src/game_loop.cpp.i
.PHONY : server_src/game_loop.i

# target to preprocess a source file
server_src/game_loop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server_src/game_loop.cpp.i
.PHONY : server_src/game_loop.cpp.i

server_src/game_loop.s: server_src/game_loop.cpp.s
.PHONY : server_src/game_loop.s

# target to generate assembly for a file
server_src/game_loop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server_src/game_loop.cpp.s
.PHONY : server_src/game_loop.cpp.s

server_src/lobby.o: server_src/lobby.cpp.o
.PHONY : server_src/lobby.o

# target to build an object file
server_src/lobby.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server_src/lobby.cpp.o
.PHONY : server_src/lobby.cpp.o

server_src/lobby.i: server_src/lobby.cpp.i
.PHONY : server_src/lobby.i

# target to preprocess a source file
server_src/lobby.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server_src/lobby.cpp.i
.PHONY : server_src/lobby.cpp.i

server_src/lobby.s: server_src/lobby.cpp.s
.PHONY : server_src/lobby.s

# target to generate assembly for a file
server_src/lobby.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server_src/lobby.cpp.s
.PHONY : server_src/lobby.cpp.s

server_src/main.o: server_src/main.cpp.o
.PHONY : server_src/main.o

# target to build an object file
server_src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server_src/main.cpp.o
.PHONY : server_src/main.cpp.o

server_src/main.i: server_src/main.cpp.i
.PHONY : server_src/main.i

# target to preprocess a source file
server_src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server_src/main.cpp.i
.PHONY : server_src/main.cpp.i

server_src/main.s: server_src/main.cpp.s
.PHONY : server_src/main.s

# target to generate assembly for a file
server_src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server_src/main.cpp.s
.PHONY : server_src/main.cpp.s

server_src/player.o: server_src/player.cpp.o
.PHONY : server_src/player.o

# target to build an object file
server_src/player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server_src/player.cpp.o
.PHONY : server_src/player.cpp.o

server_src/player.i: server_src/player.cpp.i
.PHONY : server_src/player.i

# target to preprocess a source file
server_src/player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server_src/player.cpp.i
.PHONY : server_src/player.cpp.i

server_src/player.s: server_src/player.cpp.s
.PHONY : server_src/player.s

# target to generate assembly for a file
server_src/player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server_src/player.cpp.s
.PHONY : server_src/player.cpp.s

server_src/receiver.o: server_src/receiver.cpp.o
.PHONY : server_src/receiver.o

# target to build an object file
server_src/receiver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server_src/receiver.cpp.o
.PHONY : server_src/receiver.cpp.o

server_src/receiver.i: server_src/receiver.cpp.i
.PHONY : server_src/receiver.i

# target to preprocess a source file
server_src/receiver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server_src/receiver.cpp.i
.PHONY : server_src/receiver.cpp.i

server_src/receiver.s: server_src/receiver.cpp.s
.PHONY : server_src/receiver.s

# target to generate assembly for a file
server_src/receiver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server_src/receiver.cpp.s
.PHONY : server_src/receiver.cpp.s

server_src/sender.o: server_src/sender.cpp.o
.PHONY : server_src/sender.o

# target to build an object file
server_src/sender.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server_src/sender.cpp.o
.PHONY : server_src/sender.cpp.o

server_src/sender.i: server_src/sender.cpp.i
.PHONY : server_src/sender.i

# target to preprocess a source file
server_src/sender.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server_src/sender.cpp.i
.PHONY : server_src/sender.cpp.i

server_src/sender.s: server_src/sender.cpp.s
.PHONY : server_src/sender.s

# target to generate assembly for a file
server_src/sender.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server_src/sender.cpp.s
.PHONY : server_src/sender.cpp.s

server_src/status_broadcaster.o: server_src/status_broadcaster.cpp.o
.PHONY : server_src/status_broadcaster.o

# target to build an object file
server_src/status_broadcaster.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server_src/status_broadcaster.cpp.o
.PHONY : server_src/status_broadcaster.cpp.o

server_src/status_broadcaster.i: server_src/status_broadcaster.cpp.i
.PHONY : server_src/status_broadcaster.i

# target to preprocess a source file
server_src/status_broadcaster.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server_src/status_broadcaster.cpp.i
.PHONY : server_src/status_broadcaster.cpp.i

server_src/status_broadcaster.s: server_src/status_broadcaster.cpp.s
.PHONY : server_src/status_broadcaster.s

# target to generate assembly for a file
server_src/status_broadcaster.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server_src/status_broadcaster.cpp.s
.PHONY : server_src/status_broadcaster.cpp.s

shared_src/liberror.o: shared_src/liberror.cpp.o
.PHONY : shared_src/liberror.o

# target to build an object file
shared_src/liberror.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedLib.dir/build.make CMakeFiles/SharedLib.dir/shared_src/liberror.cpp.o
.PHONY : shared_src/liberror.cpp.o

shared_src/liberror.i: shared_src/liberror.cpp.i
.PHONY : shared_src/liberror.i

# target to preprocess a source file
shared_src/liberror.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedLib.dir/build.make CMakeFiles/SharedLib.dir/shared_src/liberror.cpp.i
.PHONY : shared_src/liberror.cpp.i

shared_src/liberror.s: shared_src/liberror.cpp.s
.PHONY : shared_src/liberror.s

# target to generate assembly for a file
shared_src/liberror.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedLib.dir/build.make CMakeFiles/SharedLib.dir/shared_src/liberror.cpp.s
.PHONY : shared_src/liberror.cpp.s

shared_src/protocol.o: shared_src/protocol.cpp.o
.PHONY : shared_src/protocol.o

# target to build an object file
shared_src/protocol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedLib.dir/build.make CMakeFiles/SharedLib.dir/shared_src/protocol.cpp.o
.PHONY : shared_src/protocol.cpp.o

shared_src/protocol.i: shared_src/protocol.cpp.i
.PHONY : shared_src/protocol.i

# target to preprocess a source file
shared_src/protocol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedLib.dir/build.make CMakeFiles/SharedLib.dir/shared_src/protocol.cpp.i
.PHONY : shared_src/protocol.cpp.i

shared_src/protocol.s: shared_src/protocol.cpp.s
.PHONY : shared_src/protocol.s

# target to generate assembly for a file
shared_src/protocol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedLib.dir/build.make CMakeFiles/SharedLib.dir/shared_src/protocol.cpp.s
.PHONY : shared_src/protocol.cpp.s

shared_src/resolve_name.o: shared_src/resolve_name.cpp.o
.PHONY : shared_src/resolve_name.o

# target to build an object file
shared_src/resolve_name.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedLib.dir/build.make CMakeFiles/SharedLib.dir/shared_src/resolve_name.cpp.o
.PHONY : shared_src/resolve_name.cpp.o

shared_src/resolve_name.i: shared_src/resolve_name.cpp.i
.PHONY : shared_src/resolve_name.i

# target to preprocess a source file
shared_src/resolve_name.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedLib.dir/build.make CMakeFiles/SharedLib.dir/shared_src/resolve_name.cpp.i
.PHONY : shared_src/resolve_name.cpp.i

shared_src/resolve_name.s: shared_src/resolve_name.cpp.s
.PHONY : shared_src/resolve_name.s

# target to generate assembly for a file
shared_src/resolve_name.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedLib.dir/build.make CMakeFiles/SharedLib.dir/shared_src/resolve_name.cpp.s
.PHONY : shared_src/resolve_name.cpp.s

shared_src/resolver.o: shared_src/resolver.cpp.o
.PHONY : shared_src/resolver.o

# target to build an object file
shared_src/resolver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedLib.dir/build.make CMakeFiles/SharedLib.dir/shared_src/resolver.cpp.o
.PHONY : shared_src/resolver.cpp.o

shared_src/resolver.i: shared_src/resolver.cpp.i
.PHONY : shared_src/resolver.i

# target to preprocess a source file
shared_src/resolver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedLib.dir/build.make CMakeFiles/SharedLib.dir/shared_src/resolver.cpp.i
.PHONY : shared_src/resolver.cpp.i

shared_src/resolver.s: shared_src/resolver.cpp.s
.PHONY : shared_src/resolver.s

# target to generate assembly for a file
shared_src/resolver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedLib.dir/build.make CMakeFiles/SharedLib.dir/shared_src/resolver.cpp.s
.PHONY : shared_src/resolver.cpp.s

shared_src/resolvererror.o: shared_src/resolvererror.cpp.o
.PHONY : shared_src/resolvererror.o

# target to build an object file
shared_src/resolvererror.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedLib.dir/build.make CMakeFiles/SharedLib.dir/shared_src/resolvererror.cpp.o
.PHONY : shared_src/resolvererror.cpp.o

shared_src/resolvererror.i: shared_src/resolvererror.cpp.i
.PHONY : shared_src/resolvererror.i

# target to preprocess a source file
shared_src/resolvererror.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedLib.dir/build.make CMakeFiles/SharedLib.dir/shared_src/resolvererror.cpp.i
.PHONY : shared_src/resolvererror.cpp.i

shared_src/resolvererror.s: shared_src/resolvererror.cpp.s
.PHONY : shared_src/resolvererror.s

# target to generate assembly for a file
shared_src/resolvererror.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedLib.dir/build.make CMakeFiles/SharedLib.dir/shared_src/resolvererror.cpp.s
.PHONY : shared_src/resolvererror.cpp.s

shared_src/socket.o: shared_src/socket.cpp.o
.PHONY : shared_src/socket.o

# target to build an object file
shared_src/socket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedLib.dir/build.make CMakeFiles/SharedLib.dir/shared_src/socket.cpp.o
.PHONY : shared_src/socket.cpp.o

shared_src/socket.i: shared_src/socket.cpp.i
.PHONY : shared_src/socket.i

# target to preprocess a source file
shared_src/socket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedLib.dir/build.make CMakeFiles/SharedLib.dir/shared_src/socket.cpp.i
.PHONY : shared_src/socket.cpp.i

shared_src/socket.s: shared_src/socket.cpp.s
.PHONY : shared_src/socket.s

# target to generate assembly for a file
shared_src/socket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SharedLib.dir/build.make CMakeFiles/SharedLib.dir/shared_src/socket.cpp.s
.PHONY : shared_src/socket.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... SDL2pp"
	@echo "... SharedGameLib"
	@echo "... SharedLib"
	@echo "... box2d"
	@echo "... client"
	@echo "... glad"
	@echo "... glfw"
	@echo "... imgui"
	@echo "... sajson"
	@echo "... server"
	@echo "... testbed"
	@echo "... ui"
	@echo "... unit_test"
	@echo "... client_src/client.o"
	@echo "... client_src/client.i"
	@echo "... client_src/client.s"
	@echo "... client_src/client_main.o"
	@echo "... client_src/client_main.i"
	@echo "... client_src/client_main.s"
	@echo "... client_src/receiver.o"
	@echo "... client_src/receiver.i"
	@echo "... client_src/receiver.s"
	@echo "... client_src/sender.o"
	@echo "... client_src/sender.i"
	@echo "... client_src/sender.s"
	@echo "... game_src/beam.o"
	@echo "... game_src/beam.i"
	@echo "... game_src/beam.s"
	@echo "... game_src/game_dynamic.o"
	@echo "... game_src/game_dynamic.i"
	@echo "... game_src/game_dynamic.s"
	@echo "... game_src/game_lobby.o"
	@echo "... game_src/game_lobby.i"
	@echo "... game_src/game_lobby.s"
	@echo "... game_src/game_map.o"
	@echo "... game_src/game_map.i"
	@echo "... game_src/game_map.s"
	@echo "... game_src/move.o"
	@echo "... game_src/move.i"
	@echo "... game_src/move.s"
	@echo "... game_src/position.o"
	@echo "... game_src/position.i"
	@echo "... game_src/position.s"
	@echo "... game_src/select_map.o"
	@echo "... game_src/select_map.i"
	@echo "... game_src/select_map.s"
	@echo "... game_src/worm.o"
	@echo "... game_src/worm.i"
	@echo "... game_src/worm.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... screen.o"
	@echo "... screen.i"
	@echo "... screen.s"
	@echo "... server_src/game_loop.o"
	@echo "... server_src/game_loop.i"
	@echo "... server_src/game_loop.s"
	@echo "... server_src/lobby.o"
	@echo "... server_src/lobby.i"
	@echo "... server_src/lobby.s"
	@echo "... server_src/main.o"
	@echo "... server_src/main.i"
	@echo "... server_src/main.s"
	@echo "... server_src/player.o"
	@echo "... server_src/player.i"
	@echo "... server_src/player.s"
	@echo "... server_src/receiver.o"
	@echo "... server_src/receiver.i"
	@echo "... server_src/receiver.s"
	@echo "... server_src/sender.o"
	@echo "... server_src/sender.i"
	@echo "... server_src/sender.s"
	@echo "... server_src/status_broadcaster.o"
	@echo "... server_src/status_broadcaster.i"
	@echo "... server_src/status_broadcaster.s"
	@echo "... shared_src/liberror.o"
	@echo "... shared_src/liberror.i"
	@echo "... shared_src/liberror.s"
	@echo "... shared_src/protocol.o"
	@echo "... shared_src/protocol.i"
	@echo "... shared_src/protocol.s"
	@echo "... shared_src/resolve_name.o"
	@echo "... shared_src/resolve_name.i"
	@echo "... shared_src/resolve_name.s"
	@echo "... shared_src/resolver.o"
	@echo "... shared_src/resolver.i"
	@echo "... shared_src/resolver.s"
	@echo "... shared_src/resolvererror.o"
	@echo "... shared_src/resolvererror.i"
	@echo "... shared_src/resolvererror.s"
	@echo "... shared_src/socket.o"
	@echo "... shared_src/socket.i"
	@echo "... shared_src/socket.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

