# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/joaco/cuatri/taller/tp3_worms

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/joaco/cuatri/taller/tp3_worms

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/joaco/cuatri/taller/tp3_worms/CMakeFiles /home/joaco/cuatri/taller/tp3_worms/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/joaco/cuatri/taller/tp3_worms/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FIUUUMMMM

# Build rule for target.
FIUUUMMMM: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FIUUUMMMM
.PHONY : FIUUUMMMM

# fast build rule for target.
FIUUUMMMM/fast:
	$(MAKE) -f CMakeFiles/FIUUUMMMM.dir/build.make CMakeFiles/FIUUUMMMM.dir/build
.PHONY : FIUUUMMMM/fast

#=============================================================================
# Target rules for targets named box2d

# Build rule for target.
box2d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 box2d
.PHONY : box2d

# fast build rule for target.
box2d/fast:
	$(MAKE) -f thirdParty/box2d/src/CMakeFiles/box2d.dir/build.make thirdParty/box2d/src/CMakeFiles/box2d.dir/build
.PHONY : box2d/fast

#=============================================================================
# Target rules for targets named unit_test

# Build rule for target.
unit_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unit_test
.PHONY : unit_test

# fast build rule for target.
unit_test/fast:
	$(MAKE) -f thirdParty/box2d/unit-test/CMakeFiles/unit_test.dir/build.make thirdParty/box2d/unit-test/CMakeFiles/unit_test.dir/build
.PHONY : unit_test/fast

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) -f thirdParty/box2d/extern/glad/CMakeFiles/glad.dir/build.make thirdParty/box2d/extern/glad/CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f thirdParty/box2d/extern/glfw/CMakeFiles/glfw.dir/build.make thirdParty/box2d/extern/glfw/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) -f thirdParty/box2d/extern/imgui/CMakeFiles/imgui.dir/build.make thirdParty/box2d/extern/imgui/CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

#=============================================================================
# Target rules for targets named sajson

# Build rule for target.
sajson: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sajson
.PHONY : sajson

# fast build rule for target.
sajson/fast:
	$(MAKE) -f thirdParty/box2d/extern/sajson/CMakeFiles/sajson.dir/build.make thirdParty/box2d/extern/sajson/CMakeFiles/sajson.dir/build
.PHONY : sajson/fast

#=============================================================================
# Target rules for targets named testbed

# Build rule for target.
testbed: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testbed
.PHONY : testbed

# fast build rule for target.
testbed/fast:
	$(MAKE) -f thirdParty/box2d/testbed/CMakeFiles/testbed.dir/build.make thirdParty/box2d/testbed/CMakeFiles/testbed.dir/build
.PHONY : testbed/fast

#=============================================================================
# Target rules for targets named SDL2pp

# Build rule for target.
SDL2pp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SDL2pp
.PHONY : SDL2pp

# fast build rule for target.
SDL2pp/fast:
	$(MAKE) -f thirdParty/SDL2pp/CMakeFiles/SDL2pp.dir/build.make thirdParty/SDL2pp/CMakeFiles/SDL2pp.dir/build
.PHONY : SDL2pp/fast

game.o: game.cpp.o

.PHONY : game.o

# target to build an object file
game.cpp.o:
	$(MAKE) -f CMakeFiles/FIUUUMMMM.dir/build.make CMakeFiles/FIUUUMMMM.dir/game.cpp.o
.PHONY : game.cpp.o

game.i: game.cpp.i

.PHONY : game.i

# target to preprocess a source file
game.cpp.i:
	$(MAKE) -f CMakeFiles/FIUUUMMMM.dir/build.make CMakeFiles/FIUUUMMMM.dir/game.cpp.i
.PHONY : game.cpp.i

game.s: game.cpp.s

.PHONY : game.s

# target to generate assembly for a file
game.cpp.s:
	$(MAKE) -f CMakeFiles/FIUUUMMMM.dir/build.make CMakeFiles/FIUUUMMMM.dir/game.cpp.s
.PHONY : game.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/FIUUUMMMM.dir/build.make CMakeFiles/FIUUUMMMM.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/FIUUUMMMM.dir/build.make CMakeFiles/FIUUUMMMM.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/FIUUUMMMM.dir/build.make CMakeFiles/FIUUUMMMM.dir/main.cpp.s
.PHONY : main.cpp.s

screen.o: screen.cpp.o

.PHONY : screen.o

# target to build an object file
screen.cpp.o:
	$(MAKE) -f CMakeFiles/FIUUUMMMM.dir/build.make CMakeFiles/FIUUUMMMM.dir/screen.cpp.o
.PHONY : screen.cpp.o

screen.i: screen.cpp.i

.PHONY : screen.i

# target to preprocess a source file
screen.cpp.i:
	$(MAKE) -f CMakeFiles/FIUUUMMMM.dir/build.make CMakeFiles/FIUUUMMMM.dir/screen.cpp.i
.PHONY : screen.cpp.i

screen.s: screen.cpp.s

.PHONY : screen.s

# target to generate assembly for a file
screen.cpp.s:
	$(MAKE) -f CMakeFiles/FIUUUMMMM.dir/build.make CMakeFiles/FIUUUMMMM.dir/screen.cpp.s
.PHONY : screen.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... FIUUUMMMM"
	@echo "... box2d"
	@echo "... unit_test"
	@echo "... glad"
	@echo "... glfw"
	@echo "... imgui"
	@echo "... sajson"
	@echo "... testbed"
	@echo "... SDL2pp"
	@echo "... game.o"
	@echo "... game.i"
	@echo "... game.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... screen.o"
	@echo "... screen.i"
	@echo "... screen.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

