#ifndef CONSTANTS_GAME_H
#define CONSTANTS_GAME_H


enum /*Direction*/ {
    LEFT_DIR = 0,
    RIGHT_DIR, 
    FORWARD_DIR,
    BACKWARD_DIR,
};

enum /*EXLPOSIVE_TYPE*/{
    BAZOOKA = 0,
    GREEN_GRENADE,
    BAT,
    REMOTE_OPERATED,
    MORTAR,
    RED_GRENADE,
    BANANA,
    DYNAMITE,
    AIR_ATTACK,
    HOLY_GRENADE,
    FRAGMENT,
};

#define AMOUNT_OF_WEAPONS 10

enum /*SUPPLY_BOX_TYPE*/{
    HEALTH_SUPPLY = 0,
    MORTAR_SUPPLY,
    RED_GRENADE_SUPPLY,
    BANANA_SUPPLY,
    HOLY_GRENADE_SUPPLY,
    AIR_ATTACK_SUPPLY,
    DYNAMITE_SUPPLY,
    BAT_SUPPLY,
    REMOTE_OPERATED_SUPPLY,
    TRAP_SUPPLY,
};

enum /* CHEATS */ {
    ADD_HEALTH = 0,
    ALL_WEAPONS,
    ALL_INVINCIBLE,
    STOP_TURN,
    RENEW_TURN,
};


enum /*MATCH TYPE*/{
    NEW_MATCH = 0,
    JOIN,
    REFRESH,
};

enum /*GAME TYPE*/ {
    GAME_MAP = 0,
    GAME_DYNAMIC,
    GAME_INFO,
};

enum /*COMMAND TYPE*/ {
  COMMAND_MOVE,
  COMMAND_JUMP,
  COMMAND_ROCKET,
  COMMAND_REMOTE_OPERATED,
  COMMAND_HIT_UPCLOSE,
  COMMAND_GRENADE,
  COMMAND_CHEAT,
  COMMAND_MATCH,
  COMMAND_DYNAMITE,
};

#define WAITING 0
#define STARTED 1


#define PLAYING -1
#define ALL_LOST -2

#define INFINITE_AMUNITION -1

#endif
